title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template




title: SQL Fundamentals
description: Este curos está orientado para a utilização da linguagem Transact-SQL no Microsoft SQL Server.
theme: just-the-docs

# url: https://rramoscabral.github.io/SQL-Fundamentals/

aux_links:
  "SQL Fundamentals": 
    - "https://github.com/rramoscabral/SQL-Fundamentals"
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red