# Site settings
title: Fundamentos de SQL com T-SQL
description: Este curso é uma introdução aos fundamentos de SQL com Transact-SQL no Microsoft SQL Server.
url: "https://rramoscabral.github.io/Fundamentos-de-SQL/" 
repository: rramoscabral/Fundamentos-de-SQL
theme: just-the-docs

# Aux links for the upper right navigation
aux_links:
  "Fundamentos de SQL com T-SQL": 
    - "https://rramoscabral.github.io/Fundamentos-de-SQL"


# CODE
enable_copy_code_button: true

# Footer content

# Back to top link
back_to_top: true
back_to_top_text: "Voltar ao topo"

footer_content: ""

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html


# Color scheme
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red

  kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
