title: Fundamentos de SQL com T-SQL
description: Este cursos é uma introdução aos fundamentos de SQL com Transact-SQL no Microsoft SQL Server.
theme: just-the-docs

# url: https://rramoscabral.github.io/Fundamentos-de-SQL/

aux_links:
  "Fundamentos de SQL com T-SQL": 
    - "https://rramoscabral.github.io/Fundamentos-de-SQL"
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note 
    color: purple
  warning:
    title: Warning
    color: red